### ISSUE TITLE
implement sqrt function

### ISSUE THREAD

**Issue by FelixGibson** [BibliothecaDAO/InstaSwap#6]
Implment the u256_sqrt in utils/helper.cairo.
math detail is about Babylonian method: https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Babylonian_method

solidity version can be found at uniswapv2: https://github.com/Uniswap/v2-core/blob/master/contracts/libraries/Math.sol

**Comment by mehrdadmms** [comment]
Hey, I was looking for "good first issues" as I'm looking for a new job and bumped into this issue. 
Full disclosure, I have NO experience with Cairo but I used chatGPT to generate this based on the solidity code and the Babylonian method. Your project seems cool and I just wanted to help. 
Also, here's my [LinkedIn](https://www.linkedin.com/in/mehrdad-mms/) in case you have something that fits my skills 

```Cairo
// Define the sqrt function using the Babylonian method
function sqrt(uint y) internal pure returns (uint z) {
    if (y > 3) {
        // Initialize z to y
        z = y;

        // Divide y by 2 and add 1 to get the first estimate, x
        uint x = y / 2 + 1;

        // Iterate until convergence
        while (x < z) {
            // Set z = x
            z = x;

            // Calculate the next estimate, x
            x = (y / x + x) / 2;
        }
    } else if (y != 0) {
        // If y <= 3, set z = 1
        z = 1;
    }

    // Create a new Cairo context for drawing
    cairo_t* cr = cairo_create(surface);

    // Draw the square root symbol using Cairo
    cairo_move_to(cr, 0, 0);
    cairo_line_to(cr, 10, 10);
    cairo_line_to(cr, 20, 0);
    cairo_stroke(cr);

    // Clean up the Cairo context
    cairo_destroy(cr);
}
```

**Comment by FelixGibson** [comment]
It's great. Can you rewrite it in cairo1 and add tests fot it? @mehrdadmms
